version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket s3test.worky --output-template-file serverless-output.yaml
artifacts:
  type: zip
  files:
    - serverless-output.yaml